<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ObjectDataSourceInsert.aspx.vb" Inherits="ObjectDataSourceInsert" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            &nbsp;<asp:ObjectDataSource ID="sourceEmployees" runat="server" DataObjectTypeName="DatabaseComponent.EmployeeDetails"
                DeleteMethod="DeleteEmployee" InsertMethod="InsertEmployee" OldValuesParameterFormatString="original_{0}"
                SelectMethod="GetEmployees" TypeName="DatabaseComponent.EmployeeDB" UpdateMethod="UpdateEmployee">
            </asp:ObjectDataSource>

            <asp:DetailsView ID="detailsInsertEmployee" runat="server" DataSourceID="sourceEmployees" DefaultMode="Insert"
                AutoGenerateInsertButton="True" AutoGenerateRows="False"
                Height="50px" Width="125px" CellPadding="4"
                Font-Names="Verdana" Font-Size="Small" ForeColor="#333333" GridLines="None">
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <CommandRowStyle BackColor="#D1DDF1" Font-Bold="True" />
                <RowStyle BackColor="#EFF3FB" />
                <FieldHeaderStyle BackColor="#DEE8F5" Font-Bold="True" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <Fields>
                    <asp:BoundField InsertVisible="False" DataField="EmployeeID" HeaderText="EmployeeID" SortExpression="EmployeeID" />
                    <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                    <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                    <asp:BoundField DataField="TitleOfCourtesy" HeaderText="TitleOfCourtesy" SortExpression="TitleOfCourtesy" />
                </Fields>
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <EditRowStyle BackColor="#2461BF" />
                <AlternatingRowStyle BackColor="White" />
            </asp:DetailsView>

            <asp:Label ID="lblConfirmation" Font-Names="Verdana" Font-Size="Small" runat="server" EnableViewState="false"></asp:Label>
            <br />
            <br />

            <asp:GridView ID="gridEmployeeList" runat="server" DataSourceID="sourceEmployees" DataKeyNames="EmployeeID"
                CellPadding="4" Font-Names="Verdana" Font-Size="Small" ForeColor="#333333"
                GridLines="None" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                EnableSortingAndPagingCallbacks="True" PageSize="5">

                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <AlternatingRowStyle BackColor="White" />

                <Columns>
                    <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                    <asp:BoundField DataField="EmployeeID" InsertVisible="False" HeaderText="EmployeeID" SortExpression="EmployeeID" />
                    <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                    <asp:BoundField DataField="TitleOfCourtesy" HeaderText="TitleOfCourtesy" SortExpression="TitleOfCourtesy" />
                </Columns>
            </asp:GridView>
            &nbsp;
        </div>
    </form>
</body>
</html>
