<%@ Page Language="VB" AutoEventWireup="false" CodeFile="SqlDataSourceDelete.aspx.vb" Inherits="SqlDataSourceDelete" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <asp:SqlDataSource ID="sourceEmployees" runat="server"
ProviderName="System.Data.SqlClient"
ConnectionString="<%$ ConnectionStrings:Northwind %>"
SelectCommand=
"SELECT EmployeeID, FirstName, LastName, Title, City FROM Employees"
DeleteCommand="DELETE Employees WHERE EmployeeID=@EmployeeID ">
</asp:SqlDataSource>

        <asp:GridView ID="GridView1" runat="server" DataSourceID="sourceEmployees"
AutoGenerateDeleteButton="true" DataKeyNames="EmployeeID">
</asp:GridView>
    </div>
    </form>
</body>
</html>
